name: cresce_flutter_app
description: Cresce flutter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ui_bits: ^0.0.29
  http: ^0.12.2
  equatable: ^1.2.5
  provider: ^4.3.3
  syncfusion_localizations: ^18.1.36

dependency_overrides:
  intl: ^0.17.0
  loading:
    git:
      url: git://github.com/leonzone/loading.git
      path: loading
      ref: 8f5a63f

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.4
  hottie:
    git: https://github.com/szotp/hottie

flutter:
  generate: true
  uses-material-design: true
