name: cresce_flutter_app
description: Cresce flutter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ui_bits: ^0.0.35
  http: ^0.13.1
  equatable: ^2.0.0
  provider: ^5.0.0

dependency_overrides:
  loading:
    git:
      url: git://github.com/leonzone/loading.git
      path: loading
      ref: 8f5a63f

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.0.3

flutter:
  generate: true
  uses-material-design: true
