name: cresce_flutter_app
description: Cresce flutter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cresce_flutter_features:
    git:
      url: https://github.com/AlienEngineer/cresce-flutter-features.git
      ref: master

  ui_bits: ^0.0.3
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.0

flutter:

  uses-material-design: true
