name: Build

on:
  pull_request:
    branches: [ master, develop ]

jobs:

  build:
    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter:latest

    services:
      cresce:
        image: alienengineer/cresce
        ports:
          - 5000
          
    steps:
      - uses: actions/checkout@v2
        
      - run: |
          echo ${{ job.services.cresce.ports['5000'] }}          

      - run: curl http://localhost:${{ job.services.cresce.ports['5000'] }}
        continue-on-error: true
      
      - run: curl cresce
        continue-on-error: true
          
      - name: Print Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
