name: Build

on:
  pull_request:
    branches: [ master, develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    services:
      cresce:
        image: alienengineer/cresce
        options: "--name cresceapi"
        ports:
          - 5000
          
    steps:
      - uses: actions/checkout@v2
        
      - run: |
          echo ${{ job.services.cresce.ports['5000'] }}          
      
      - name: health check via action name
        run: curl http://localhost:5000
        continue-on-error: true 
          
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.6'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
        env: 
          host: http://cresce/

      - name: print logs
        if: failure()
        run: docker logs "${{ job.services.cresce.id }}"
