name: Build

on:
  pull_request:
    branches: [ master, develop ]

jobs:

  build:
    runs-on: ubuntu-latest

    container:
      image:  node:10.16-jessie

    services:
      cresce:
        image: alienengineer/cresce
        ports:
        - 5000

    steps:
      - uses: actions/checkout@v2

      - name: health check via action name
        run: curl http://cresce/

      - name: Install Flutter
        uses: subosito/flutter-action@v1.4.0

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
        env:
          host: http://cresce/

      - name: print logs
        if: failure()
        run: curl http://cresce/logs
