name: Build

on:
  pull_request:
    branches: [ master, develop ]

jobs:

  build:
    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter:latest

    services:
      cresce:
        image: alienengineer/cresce
        options: "--name cresceapi"
        ports:
          - 5000
          
    steps:
      - uses: actions/checkout@v2
        
      - run: |
          echo ${{ job.services.cresce.ports['5000'] }}          
      
      - name: health check via action name
        run: curl http://cresce
          
      - name: Print Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
        env: 
          host: http://cresce/

      - name: print logs
        run: docker logs "${{ job.services.cresce.id }}"
