name: Build

on:
  pull_request:
    branches: [ master, develop ]

jobs:

  build:
    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter:latest

    services:
      cresce.api:
        image: alienengineer/cresce
        ports:
          - 80
          
    steps:
      - uses: actions/checkout@v2
        
      - run: echo ${{ job.services.cresce.api.ports['80'] }}

      - name: Print Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
