name: Create-Apk

on:
  push:
    branches: [ master]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter:latest

    steps:
      - uses: actions/checkout@v2

      - name: Print Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk
