name: Flutter

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
       cresce-api:
         image: alienengineer/cresce
         ports:
           - 5000:80
         options: >-
          --health-cmd "curl --fail -s http://localhost:5000/ || exit 1" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    container:
      image:  cirrusci/flutter:latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Get health check end point
        continue-on-error: true
        run: |
          curl http://localhost:5000

      - name: Print Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
