name: Flutter

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      cresce-api:
        image: alienengineer/cresce
        ports:
          - 5000:80

    container:
      image:  cirrusci/flutter:latest

    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: https://localhost:5000|http://localhost:5000
          follow-redirect: no # Optional, defaults to "no"
          max-attempts: 10 # Optional, defaults to 1
          retry-delay: 5s # Optional, only applicable to max-attempts > 1

      - uses: actions/checkout@v2

      - name: Print Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test