name: Flutter

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      cresce-api:
        image: alienengineer/cresce
        ports:
          - 5000:80
        options: --health-cmd="curl --location --request GET '127.0.0.1:5000'" --health-interval=10s --health-timeout=5s --health-retries=3

    container:
      image:  cirrusci/flutter:latest

    steps:
      - uses: actions/checkout@v2

      - name: Print Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test